language: node_js
node_js:
  - "stable"

services:
  - postgresql

before_script:
  -psql -c "create user amiyt with password 'postgres';" -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
 
script:
  - npm run test
notifications:
  email: false

env:
  global:
    - export NODE_ENV=test


after_success:
  - npm run coverage
  - npm run coveralls

cache:
  directories:
    - node_modules
