language: node_js
node_js:
- "stable"

services:
  - postgresql

postgres:
  adapter: postgresql
  database: myDiary
  username: postgres

before_script:
  - npm install
 - psql -c 'create database myDiary;' -U postgres

notifications:
  email: false

env:
  global:
  - export NODE_ENV=test

script:
  - npm run test
after_success:
  - npm run coverage
  - npm run coveralls

cache:
  directories:
    - node_modules
